IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[KC_TABLE]') AND TYPE = N'U')
BEGIN
  CREATE TABLE [dbo].[KC_TABLE](
    [INTERNAL_ID] [int] IDENTITY(1,1) NOT NULL,
    [INTERNAL_NUM] [numeric](9, 0) NULL,
    [USER_DEF7] [numeric](19, 5) NOT NULL
	) ON [PRIMARY]
  ;
	ALTER TABLE [dbo].[KC_TABLE] ADD DEFAULT ((0)) FOR [USER_DEF7]
	;
END
;
GO
;
